---

- name: user before become
  set_fact:
    home_befor_become: "{{ ansible_env.HOME }}"

- name: Install npm packages globally
  shell: 'bash -c "source {{ home_befor_become }}/.nvm/nvm.sh  && npm i -g {{ item }}"'
  with_items:
    - '--unsafe-perm ngrok'
    - 'truffle@4.1.8'
    - 'lerna@2.9.0'
    - 'transmute-cli'
