---

- name: Install nvm
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh
    creates={{ ansible_env.HOME }}/.nvm/nvm.sh

- name: Install node and set version
  shell: >
    /bin/bash -c "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm ls-remote --lts=carbon && \
    nvm install --lts=carbon && nvm alias default lts/carbon && nvm use default"
    creates={{ ansible_env.HOME }}/.nvm/alias
