---
- name: check is need become
  set_fact:
    minicube_as_root: "yes"
  when: minikube_vm_driver == "none"

- name: start minikube
  shell: "minikube start  --kubernetes-version {{ kubernetes_version }} -disk-size {{ minikube_disk_size }} --cpus {{ minikube_cpus }} --memory {{ minikube_memory }} --vm-driver={{ minikube_vm_driver }}"
  become: "{{ minikube_as_root }}"
