---
- name: Install kong
  shell: "helm install stable/kong --name gateway --set proxy.useTLS=false"

- name: spin up
  shell: "$(npm root -g)/transmute-cli/scripts/w8s/ready.w8 gateway-postgresql default"

- name: EXCLUDE_POD
  shell: "EXCLUDE_POD=gateway-kong-migration $(npm root -g)/transmute-cli/scripts/w8s/ready.w8 gateway-kong default"

