---
- name: Install kong
  shell: "helm install stable/kong --name gateway --set proxy.useTLS=false"

- name: spin up
  shell: "$(npm root -g)/transmute-cli/scripts/w8s/ready.w8 gateway-postgresql default"

- name: gateway-kong-migration
  shell: "$(npm root -g)/transmute-cli/scripts/w8s/ready.w8 gateway-kong default"

- name: EXCLUDE_POD
  shell: "$(npm root -g)/transmute-cli/scripts/w8s/ready.w8 gateway-kong default"

- name: KONG_ADMIN_URL
  shell: "PATH=$HOME/.transmute/bin:$PATH minikube service gateway-kong-admin --url | sed 's,http://,https://,g'"
  register: KONG_ADMIN_URL

- name: KONG_PROXY_URL
  shell: "PATH=$HOME/.transmute/bin:$PATH minikube service gateway-kong-proxy --url"
  register: KONG_PROXY_URL

- name: KONG_PROXY_PORT
  shell: "PATH=$HOME/.transmute/bin:$PATH kubectl get service gateway-kong-proxy -o json | jq -r '.spec.ports[0].nodePort'"
  register: KONG_PROXY_PORT

- name: KONG_HOST
  shell: "$(echo $KONG_ADMIN_URL | sed 's!https://!!g' | cut -f1 -d:)"
  register: KONG_HOST

- name: KONG_PORT
  shell: "$(echo $KONG_ADMIN_URL | sed 's!https://!!g' | cut -f2 -d:)"
  register: KONG_PORT
