---
- name: helm repo add
  shell: "helm repo add fabric8 https://fabric8.io/helm"

- name: helm status elasticsearch
  shell: "helm status elasticsearch | grep STATUS: | awk  '{print $2}' | sed 's/DEPLOYED/yes/g'"
  register: output

- name: helm install
  shell: "helm install fabric8/elasticsearch"
  when: not output.stdout

- name: create storage
  shell:
    cmd: |
      cat <<EOF | kubectl apply -f -
      kind: StorageClass
      apiVersion: storage.k8s.io/v1beta1
      metadata:
        name: standard
      provisioner: kubernetes.io/no-provisioner
      EOF
  ignore_errors: yes
