---
- name: helm repo add
  shell: "helm repo add fabric8 https://fabric8.io/helm"

- name: helm install
  shell: "helm upgrade --install elasticsearch fabric8/elasticsearch"

- name: remove default sc
  shell: "kubectl delete sc default"

- name: create storage
  shell:
    cmd: |
      cat <<EOF | kubectl apply -f -
      kind: StorageClass
      apiVersion: storage.k8s.io/v1beta1
      metadata:
        name: standard
      provisioner: kubernetes.io/no-provisioner
      parameters:
        type: gp2
      EOF
