{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "ipfs.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config: |-
{{ toYaml .Values.configmap | indent 4 }}
{{- end }}
