---
- name: transmute
  vars:
    fix_dotfiles: true
    transmute_kube_version: "v1.9.4"
  hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: dotfiles_install
      when: fix_dotfiles
    - role: dependencies
    - role: nvm
