---
- name: create directory for boto
  file:
    path: "{{ ansible_env.HOME }}/.aws"
    state: directory

- name: generate config for boto
  template:
    src: credentials.j2
    dest: "{{ ansible_env.HOME }}/.aws/credentials"

- name: create s3 bucket
  s3_bucket:
    name: "terraform.{{ clusterName }}"
    region: "{{ aws_region }}"

- name: create temporary directory TERRAFORM_TMP
  tempfile:
    state: directory
    suffix: TERRAFORM_TMP
  register: terraform_tmp

- name: generate terraform config
  template:
    src: transmute-aws.tf.j2
    dest: "{{ terraform_tmp.path }}/transmute-aws.tf"

- name: terrafrom apply
  shell: "terraform apply {{ terraform_tmp.path }}/transmute-aws.tf"
