---
- name: create directory for boto
  file:
    path: "{{ ansible_env.HOME }}/.aws"
    state: directory

- name: generate config for boto
  template:
    src: credentials.j2
    dest: "{{ ansible_env.HOME }}/.aws/credentials"

- name: create s3 bucket
  s3_bucket:
    name: "terraform.{{ clusterName }}"
    region: "{{ aws_region }}"

- name: get path
  shell: "echo $(npm root -g)'/transmute-cli/components/terraform/'"
  register: terraform

- name: generate config for boto
  template:
    src: backend.tf.j2
    dest: "{{ terraform.stdout }}/backend.tf"

- name: terraform init
  shell: "terraform init"
  args:
    chdir: '{{ terraform.stdout }}'

- name: terraform apply
  shell: "terraform apply -no-color -input=false -auto-approve=true -lock=true -var region={{ aws_region }} -var cluster-name={{ clusterName }} -var aws_key={{ aws_key }} -var aws_secret={{ aws_secret }}"
  args:
    chdir: '{{ terraform.stdout }}'

- name: get credintials
  shell: "terraform output config-map-aws-auth | kubectl apply -f -"
  args:
    chdir: '{{ terraform.stdout }}'
