---
- name: create directory for boto
  file:
    path: "{{ ansible_env.HOME }}/.aws"
    state: directory

- name: generate config for boto
  template:
    src: credentials.j2
    dest: "{{ ansible_env.HOME }}/.aws/credentials"

- name: create s3 bucket
  s3_bucket:
    name: "terraform.{{ clusterName }}"
    region: "{{ aws_region }}"

- name: get path
  shell: "echo $(npm root -g)'/transmute-cli/components/terraform/layers/cluster'"
  register: terraform

- name: terraform init
  shell: 'export TF_VAR_bucket=terraform.{{ clusterName }} && export TF_VAR_aws_region={{ aws_region }} && export TF_VAR_cluster_name={{ clusterName }} && export TF_VAR_aws_key=aws_key && export TF_VAR_aws_secret=aws_secret && terraform init'
  args:
    chdir: '{{ terraform.stdout }}'

- name: terraform apply
  shell: "export TF_VAR_aws_region={{ aws_region }} && export TF_VAR_cluster_name={{ clusterName }} && export TF_VAR_aws_key=aws_key && export TF_VAR_aws_secret=aws_secret && terraform apply -no-color -input=false -auto-approve=true -lock=true -var-file=../global.tfvars"
  args:
    chdir: '{{ terraform.stdout }}'

- name: get credintials
  shell: "export TF_VAR_aws_region={{ aws_region }} && export TF_VAR_cluster_name={{ clusterName }} && export TF_VAR_aws_key=aws_key && export TF_VAR_aws_secret=aws_secret && terraform output kubeconfig-aws-1-10 > ~/.kube/config"
  args:
    chdir: '{{ terraform.stdout }}'
