---
- name: install ipfs
  shell: "helm install stable/ipfs --name decentralized-storage --namespace alpha"

- name: install transmute-ipfs
  shell: "helm install ./transmute-ipfs --name transmute-ipfs-dev"
