---
- name: Start ganache
  shell: "helm install --name ganache transmute-charts/ganache"

- name: ready.w8 ganache
  shell: "$(npm root -g)/transmute-cli/scripts/w8s/ready.w8 ganache default"

- name: minikube_ip
  shell: "minikube ip"
  register: minikube_ip

- name: add ganache.transmute.minikube to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: '{{ minikube_ip.stdout }} ganache.transmute.minikube'
  become: yes

- name: minikube_ip
  shell: "minikube ip"
  register: minikube_ip

- name: GANACHE_CLUSTER_IP
  shell: "kubectl get service ganache -o json | jq -r '.spec.clusterIP'"
  register: GANACHE_CLUSTER_IP
