---
#
#  check_cmd brew

#  install_socat
#  set +e
#  brew install gnupg < /dev/null
#  set -e
#  install_mac_virtualbox
#  mackubectl
#  macminikube
#  machelm
#  macnsenter
#  install_certbot
#  install_jq
#  transmute_env_install
#  transmute_cli_install
