---
- name: install homebrews
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - kubectl
    - virtualbox
    - helm
    - coreutils
    - curl
    - git
    - socat
    - jq

- name: install kubernetes-cli
  homebrew:
    name: "kubernetes-cli"
    state: link

- name: install gnupg
  homebrew:
    name: "gnupg"
    state: present
  ignore_errors: yes

- name: install minikube
  homebrew:
    name: "minikube"
    state: present
    options: cask

- name: install virtualbox
  homebrew:
    name: "virtualbox"
    state: present
    options: cask


